name: ðŸš€ On push to main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: ðŸ”– Tag and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker-image:
    name: ðŸ³ Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags --always --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push API image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          file: ./Dockerfile.api
          tags: |
            ghcr.io/leoralph/rinha-de-backend-2025-api:${{ steps.get_tag.outputs.tag }}
            ghcr.io/leoralph/rinha-de-backend-2025-api:latest

      - name: Build and push worker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          file: ./Dockerfile.worker
          tags: |
            ghcr.io/leoralph/rinha-de-backend-2025-worker:${{ steps.get_tag.outputs.tag }}
            ghcr.io/leoralph/rinha-de-backend-2025-worker:latest
